# Generated by Django 3.1.5 on 2021-05-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210519_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='discription',
            new_name='description',
        ),
    ]
