# Generated by Django 3.1.5 on 2021-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='adv_end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advertise',
            name='adv_start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
