# Generated by Django 3.1.5 on 2021-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20210519_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='adv_created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_updated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
