# Generated by Django 3.1.5 on 2021-05-19 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20210519_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
